# docker-compose.yml
# ----------------------------------------------------------------------------
# Composes Docker containers and volumes to a runnable Nexus3 instance
# ----------------------------------------------------------------------------
#
---
version: '3.9'

services:

  nexus3:
    image: sonatype/nexus3:3.43.0
    ports:
      - "18081:8081"
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms2703M -Xmx2703M -XX:MaxDirectMemorySize=2703M -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
      NEXUS_SECURITY_RANDOMPASSWORD: "false"
      NEXUS_CONTEXT: ""
    volumes:
      - nexus-data:/nexus-data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready", "--username", "postgres" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

volumes:

  nexus-data:
